import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Ketrox",
  description: "Generated by create next app",
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen overflow-hidden">
      <div>
        {children}
      </div>
    </div>
  );
}
