import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen w-screen flex items-center justify-between">
        <div className="w-1/2 h-full p-4">
          <Image
            src="/images/login-bg.jpg"
            alt="Logo"
            width={2000}
            height={2000}
            priority
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="w-1/2 h-full flex items-center justify-center p-4">
          {children}
        </div>
    </div>
  );
}
